name: Build PKG Converter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Android app
        run: |
          unzip -q PKGConverterAndroid.zip -d project
          cd project
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PKG-Converter-APK
          path: "project/**/build/outputs/apk/debug/*.apk"
